// <auto-generated />
using ContactEngine.ContactContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactEngine.ContactData.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ContactEngine.ContactData.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Email = "DavidSmith1@gmail.com",
                            Name = "David Smith 01",
                            Phone = "1234567890"
                        },
                        new
                        {
                            ContactId = 2,
                            Email = "DavidSmith2@gmail.com",
                            Name = "David Smith 02",
                            Phone = "2234567890"
                        },
                        new
                        {
                            ContactId = 3,
                            Email = "DavidSmith3@gmail.com",
                            Name = "David Smith 03",
                            Phone = "3234567890"
                        },
                        new
                        {
                            ContactId = 4,
                            Email = "DavidSmith4@gmail.com",
                            Name = "David Smith 04",
                            Phone = "4234567890"
                        },
                        new
                        {
                            ContactId = 5,
                            Email = "DavidSmith5@gmail.com",
                            Name = "David Smith 05",
                            Phone = "5234567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
